export const GET_ALL_MEMBERS_REQUEST = 'GET_ALL_MEMBERS_REQUEST';
export const GET_ALL_MEMBERS_SUCCESS = 'GET_ALL_MEMBERS_SUCCESS';
export const GET_ALL_MEMBERS_FAILURE = 'GET_ALL_MEMBERS_FAILURE';
export const GET_ONE_MEMBER_SUCCESS = 'GET_ONE_MEMBER_SUCCESS';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
